function generateRandomDocumentNumber() {
  const letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  const numbers = "0123456789";
  let documentNumber = "LDN-";

  // Create a random document number of length 12 with letters and numbers, divided into 3 groups of 4
  for (let i = 0; i < 3; i++) {
    for (let j = 0; j < 4; j++) {
      if (Math.random() < 0.5) {
        documentNumber += letters.charAt(
          Math.floor(Math.random() * letters.length)
        );
      } else {
        documentNumber += numbers.charAt(
          Math.floor(Math.random() * numbers.length)
        );
      }
    }
    if (i < 2) {
      documentNumber += "-";
    }
  }
  return documentNumber;
}
const timeOffs = [
  {
    document_no: generateRandomDocumentNumber(),
    name: "Juan Gomez",
    position: "Sales Manager",
    leave_type: "Vacation Leave",
    leave_from: "2024-07-26",
    leave_to: "2024-07-26",
    transaction_date: "2024-07-24",
    status: "Approved",
    endorsed_date: "2024-07-24",
    endorsed_by: "Maria Lopez",
    reasons: "Annual vacation to relax and recharge.",
    reference_number: "REF-2024-1011",
    employee: {
      employee_id: "ITI-12345",
      name: "Alice Johnson",
      department: "Sales",
      position: "Sales Associate",
    },
    approver_details: {
      approver_id: 67890,
      name: "Juan Gomez",
      position: "Sales Manager",
      department: "Sales",
    },
  },
  {
    document_no: generateRandomDocumentNumber(),
    name: "Fred Del Pilar",
    position: "Frontend Developer",
    leave_type: "Vacation Leave",
    leave_from: "2024-07-26",
    leave_to: "2024-07-26",
    transaction_date: "2024-07-24",
    status: "Approved",
    endorsed_date: "2024-07-24",
    endorsed_by: "Sarah Lee",
    reasons: "Personal time off.",
    reference_number: "REF-2024-1012",
    employee: {
      employee_id: "ITI-67891",
      name: "John Doe",
      department: "Development",
      position: "Frontend Developer",
    },
    approver_details: {
      approver_id: 98765,
      name: "Fred Del Pilar",
      position: "Frontend Developer",
      department: "Development",
    },
  },
  {
    document_no: generateRandomDocumentNumber(),
    name: "Kenjie Gutierrez",
    position: "UI/UX Developer",
    leave_type: "Vacation Leave",
    leave_from: "2024-07-26",
    leave_to: "2024-07-26",
    transaction_date: "2024-07-24",
    status: "Approved",
    approve_date: "2024-07-24",
    endorsed_date: "2024-07-24",
    endorsed_by: "Maria Lopez",
    reasons: "Rest and relaxation.",
    reference_number: "REF-2024-1013",
    employee: {
      employee_id: 67892,
      name: "Emily Davis",
      department: "Design",
      position: "UI/UX Developer",
    },
    approver_details: {
      approver_id: "ITI-67892",
      name: "Kenjie Gutierrez",
      position: "UI/UX Developer",
      department: "Design",
    },
  },
  {
    document_no: generateRandomDocumentNumber(),
    name: "Francis Custodio",
    position: "Backend Developer",
    leave_type: "Vacation Leave",
    leave_from: "2024-07-26",
    leave_to: "2024-07-26",
    transaction_date: "2024-07-24",
    status: "Cancelled",
    endorsed_date: "2024-07-24",
    endorsed_by: "Maria Lopez",
    reasons: "Change of plans.",
    reference_number: "REF-2024-1014",
    employee: {
      employee_id: "ITI-67893",
      name: "Michael Brown",
      department: "Backend",
      position: "Backend Developer",
    },
    approver_details: {
      approver_id: 67893,
      name: "Francis Custodio",
      position: "Backend Developer",
      department: "Backend",
    },
  },
  {
    document_no: generateRandomDocumentNumber(),
    name: "Sharmaine Rivera",
    position: "Web Developer",
    leave_type: "Vacation Leave",
    leave_from: "2024-07-26",
    leave_to: "2024-07-26",
    transaction_date: "2024-07-24",
    status: "Filed",
    approve_date: "2024-07-24",
    endorsed_date: "2024-07-24",
    endorsed_by: "Maria Lopez",
    reasons: "Holiday.",
    reference_number: "REF-2024-1015",
    employee: {
      employee_id: "ITI-67894",
      name: "Sarah Wilson",
      department: "Web Development",
      position: "Web Developer",
    },
    approver_details: {
      approver_id: 67894,
      name: "Sharmaine Rivera",
      position: "Web Developer",
      department: "Web Development",
    },
  },
  {
    document_no: generateRandomDocumentNumber(),
    name: "Andrei Anecito",
    position: "Mobile Developer",
    leave_type: "Sick Leave",
    leave_from: "2024-07-26",
    leave_to: "2024-07-26",
    transaction_date: "2024-07-25",
    status: "Filed",
    approve_date: "2024-07-24",
    endorsed_date: "2024-07-24",
    endorsed_by: "Maria Lopez",
    reasons: "Medical condition.",
    reference_number: "REF-2024-1001",
    employee: {
      employee_id: "ITI-67895",
      name: "Daniel Harris",
      department: "Mobile Development",
      position: "Mobile Developer",
    },
    approver_details: {
      approver_id: 67895,
      name: "Andrei Anecito",
      position: "Mobile Developer",
      department: "Mobile Development",
    },
  },
  {
    document_no: generateRandomDocumentNumber(),
    name: "Jiro Arceo",
    position: "Quality Assurance",
    leave_type: "Sick Leave",
    leave_from: "2024-07-27",
    leave_to: "2024-07-27",
    transaction_date: "2024-07-26",
    status: "Filed",
    approve_date: "2024-07-24",
    endorsed_date: "2024-07-24",
    endorsed_by: "Maria Lopez",
    reasons: "Illness.",
    reference_number: "REF-2024-1002",
    employee: {
      employee_id: "ITI-67896",
      name: "Sophia Carter",
      department: "Quality Assurance",
      position: "Quality Assurance",
    },
    approver_details: {
      approver_id: 67896,
      name: "Jiro Arceo",
      position: "Quality Assurance",
      department: "Quality Assurance",
    },
  },
  {
    document_no: generateRandomDocumentNumber(),
    name: "Angel Mariano",
    position: "Project Manager",
    leave_type: "Sick Leave",
    leave_from: "2024-07-30",
    leave_to: "2024-07-30",
    transaction_date: "2024-07-27",
    status: "Cancelled",
    endorsed_date: "2024-07-27",
    endorsed_by: "Sarah Lee",
    reasons: "Medical issue.",
    reference_number: "REF-2024-1003",
    employee: {
      employee_id: "ITI-67897",
      name: "Liam Johnson",
      department: "Project Management",
      position: "Project Manager",
    },
    approver_details: {
      approver_id: 67897,
      name: "Angel Mariano",
      position: "Project Manager",
      department: "Project Management",
    },
  },
  {
    document_no: generateRandomDocumentNumber(),
    name: "Juan Dela Cruz",
    position: "IT Director",
    leave_type: "Paternal Leave",
    leave_from: "2024-07-30",
    leave_to: "2024-08-30",
    transaction_date: "2024-07-28",
    status: "Filed",
    approve_date: "2024-07-24",
    endorsed_date: "2024-07-24",
    endorsed_by: "Maria Lopez",
    reasons: "Family leave.",
    reference_number: "REF-2024-1004",
    employee: {
      employee_id: "ITI-67898",
      name: "Jessica Taylor",
      department: "IT",
      position: "IT Director",
    },
    approver_details: {
      approver_id: 67898,
      name: "Juan Dela Cruz",
      position: "IT Director",
      department: "IT",
    },
  },
  {
    document_no: generateRandomDocumentNumber(),
    name: "Carlo Buenaventura",
    position: "Administrator",
    leave_type: "Bereavement Leave",
    leave_from: "2024-07-30",
    leave_to: "2024-07-30",
    transaction_date: "2024-07-29",
    status: "Approved",
    endorsed_date: "2024-07-29",
    endorsed_by: "Maria Lopez",
    reasons: "Family loss.",
    reference_number: "REF-2024-1005",
    employee: {
      employee_id: "ITI-67899",
      name: "Robert Miller",
      department: "Administration",
      position: "Administrator",
    },
    approver_details: {
      approver_id: 67899,
      name: "Carlo Buenaventura",
      position: "Administrator",
      department: "Administration",
    },
  },
  {
    document_no: generateRandomDocumentNumber(),
    name: "Juan Gomez",
    position: "Business Analyst",
    leave_type: "Vacation Leave",
    leave_from: "2024-12-30",
    leave_to: "2024-12-30",
    transaction_date: "2024-07-30",
    status: "Filed",
    approve_date: "2024-07-24",
    endorsed_date: "2024-07-24",
    endorsed_by: "Maria Lopez",
    reasons: "End of year vacation.",
    reference_number: "REF-2024-1006",
    employee: {
      employee_id: "ITI-67900",
      name: "Laura Green",
      department: "Business Analysis",
      position: "Business Analyst",
    },
    approver_details: {
      approver_id: 67900,
      name: "Juan Gomez",
      position: "Business Analyst",
      department: "Business Analysis",
    },
  },
  {
    document_no: generateRandomDocumentNumber(),
    name: "Miko Dela Cruz",
    position: "Full Stack Developer",
    leave_type: "Sick Leave",
    leave_from: "2024-07-30",
    leave_to: "2024-07-30",
    transaction_date: "2024-06-26",
    status: "Approved",
    endorsed_date: "2024-06-26",
    endorsed_by: "Sarah Lee",
    reasons: "Health issues.",
    reference_number: "REF-2024-1007",
    employee: {
      employee_id: "ITI-67901",
      name: "James Wilson",
      department: "Development",
      position: "Full Stack Developer",
    },
    approver_details: {
      approver_id: 67901,
      name: "Miko Dela Cruz",
      position: "Full Stack Developer",
      department: "Development",
    },
  },
  {
    document_no: generateRandomDocumentNumber(),
    name: "Anna Dela Pena",
    position: "Technical Support",
    leave_type: "Maternity Leave",
    leave_from: "2024-07-30",
    leave_to: "2025-04-30",
    transaction_date: "2024-06-27",
    status: "Approved",
    endorsed_date: "2024-06-27",
    endorsed_by: "Maria Lopez",
    reasons: "Maternity leave.",
    reference_number: "REF-2024-1008",
    employee: {
      employee_id: "ITI-67902",
      name: "Linda Martinez",
      department: "Technical Support",
      position: "Technical Support",
    },
    approver_details: {
      approver_id: 67902,
      name: "Anna Dela Pena",
      position: "Technical Support",
      department: "Technical Support",
    },
  },
  {
    document_no: generateRandomDocumentNumber(),
    name: "Margareth Domingo",
    position: "Admin Assistant",
    leave_type: "Sick Leave",
    leave_from: "2024-07-30",
    leave_to: "2024-07-30",
    transaction_date: "2024-06-28",
    status: "Filed",
    approve_date: "2024-07-24",
    endorsed_date: "2024-07-24",
    endorsed_by: "Maria Lopez",
    reasons: "Medical reasons.",
    reference_number: "REF-2024-1009",
    employee: {
      employee_id: "ITI-67903",
      name: "Sophia Clark",
      department: "Administration",
      position: "Admin Assistant",
    },
    approver_details: {
      approver_id: 67903,
      name: "Margareth Domingo",
      position: "Admin Assistant",
      department: "Administration",
    },
  },
  {
    document_no: generateRandomDocumentNumber(),
    name: "Jimmy Santos",
    position: "CEO",
    leave_type: "Vacation Leave",
    leave_from: "2024-07-30",
    leave_to: "2024-07-30",
    transaction_date: "2024-06-29",
    status: "Filed",
    approve_date: "2024-07-24",
    endorsed_date: "2024-07-24",
    endorsed_by: "Maria Lopez",
    reasons: "Personal retreat.",
    reference_number: "REF-2024-1010",
    employee: {
      employee_id: "ITI-67904",
      name: "David Turner",
      department: "Executive",
      position: "CEO",
    },
    approver_details: {
      approver_id: 67904,
      name: "Jimmy Santos",
      position: "CEO",
      department: "Executive",
    },
  },
];

export const TimeOffService = {
  getTimeOff() {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve(timeOffs);
      }, 1000);
    });
  },
};
